# Generated by Django 2.1.2 on 2019-01-07 07:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0002_auto_20190107_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=64, verbose_name='Last Name')),
                ('biography', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Source Name')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Source Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g. website url, facebook_id,twitter tag,..)', max_length=128, verbose_name='Reference')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete='cascade', related_name='article', to='article_management.ArticleAuthor'),
        ),
        migrations.AlterField(
            model_name='articlecateory',
            name='desc',
            field=models.TextField(blank=True, default='', verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='articlecateory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Category Name'),
        ),
    ]
