# Generated by Django 2.1.2 on 2019-01-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0003_auto_20190107_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete='cascade', related_name='article_author', to='article_management.ArticleAuthor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete='cascade', related_name='article_category', to='article_management.ArticleCateory'),
        ),
    ]
