# Generated by Django 2.1.2 on 2019-01-07 15:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=512)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('slug', models.CharField(blank=True, default=models.CharField(max_length=512), help_text='Slug will be generated automatically from the title of the post', max_length=120, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCateory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Category Name')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Category Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Source Name')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Source Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g. website url, facebook_id,twitter tag,..)', max_length=128, verbose_name='Reference')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete='cascade', related_name='news', to='news_management.NewsCateory'),
        ),
    ]
