# Generated by Django 2.1.2 on 2019-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete='cascade', related_name='news_category', to='news_management.NewsCateory'),
        ),
    ]
