# Generated by Django 2.1.2 on 2019-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0002_auto_20190107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscateory',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Category Name'),
        ),
    ]
