# Generated by Django 2.1.2 on 2019-01-07 17:34

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Area Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 7, 17, 34, 51, 1917, tzinfo=utc), editable=False)),
            ],
            options={
                'ordering': ['destrict'],
            },
        ),
        migrations.CreateModel(
            name='Destrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Destrict Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 7, 17, 34, 51, 1917, tzinfo=utc), editable=False)),
            ],
            options={
                'ordering': ['province'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Province Name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 7, 17, 34, 51, 1917, tzinfo=utc), editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='destrict',
            name='province',
            field=models.ForeignKey(on_delete='cascade', related_name='province', to='afghanistan_info_management.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='area',
            name='destrict',
            field=models.ForeignKey(on_delete='cascade', related_name='destrict', to='afghanistan_info_management.Province', verbose_name='Destrict'),
        ),
    ]
