# Generated by Django 2.1.2 on 2019-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afghanistan_info_management', '0002_auto_20190107_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='destrict',
            field=models.ForeignKey(on_delete='cascade', related_name='destrict', to='afghanistan_info_management.Destrict', verbose_name='Destrict'),
        ),
    ]
