# Generated by Django 2.1.2 on 2019-01-07 17:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Entity Name')),
                ('slug', models.CharField(blank=True, help_text='Slug will be generated automatically', max_length=120, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512, verbose_name='Job Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('expire_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('entity', models.ForeignKey(on_delete='cascade', related_name='job_entity', to='job_management.Entity', verbose_name='Entity')),
            ],
            options={
                'ordering': ['-expire_date'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Category Name')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Category Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
